# Generated by Django 6.0.6 on 2026-07-01 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_exercise_assignedexercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='attention_notes',
            field=models.TextField(blank=True, help_text='Зверніть увагу (на що дивитись під час виконання)'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='camera_setup_photo',
            field=models.URLField(blank=True, help_text='Фото: як правильно поставити камеру'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='video_url',
            field=models.URLField(blank=True, help_text='Посилання на відео інструкцію'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=models.TextField(blank=True, help_text='Текст/опис вправи'),
        ),
    ]
